## Heart Disease Prediction

In [1]:
#import libraries
import tensorflow as tf
import pandas as pd
import keras
from keras.utils import FeatureSpace
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split

In [2]:
# import dataset
df = pd.read_csv("framingham.csv")

In [3]:
df.shape

(4240, 16)

In [4]:
df.columns

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [5]:
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [6]:
df.corr(numeric_only=True)

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
male,1.000000,-0.029014,0.017415,0.197026,0.317143,-0.052504,-0.004550,0.005853,0.015693,-0.070413,-0.035879,0.058199,0.081871,-0.116932,0.005979,0.088374
age,-0.029014,1.000000,-0.166356,-0.213662,-0.192959,0.123052,0.057679,0.306799,0.101314,0.262554,0.394053,0.205586,0.136096,-0.012843,0.122356,0.225408
education,0.017415,-0.166356,1.000000,0.018528,0.008323,-0.010898,-0.035142,-0.081726,-0.038749,-0.023613,-0.129496,-0.061919,-0.137747,-0.054182,-0.035843,-0.054248
currentSmoker,0.197026,-0.213662,0.018528,1.000000,0.769774,-0.048927,-0.032980,-0.103710,-0.044285,-0.046488,-0.130281,-0.107933,-0.167857,0.062686,-0.056726,0.019448
cigsPerDay,0.317143,-0.192959,0.008323,0.769774,1.000000,-0.046155,-0.032711,-0.066645,-0.037089,-0.026479,-0.088797,-0.056715,-0.093293,0.075564,-0.058886,0.057755
BPMeds,-0.052504,0.123052,-0.010898,-0.048927,-0.046155,1.000000,0.117370,0.261067,0.052060,0.080623,0.254194,0.194122,0.100702,0.015230,0.051197,0.087519
prevalentStroke,-0.004550,0.057679,-0.035142,-0.032980,-0.032711,0.117370,1.000000,0.074791,0.006955,0.000105,0.057000,0.045153,0.025909,-0.017674,0.018440,0.061823
prevalentHyp,0.005853,0.306799,-0.081726,-0.103710,-0.066645,0.261067,0.074791,1.000000,0.077752,0.163632,0.696656,0.615840,0.301344,0.146815,0.086656,0.177458
diabetes,0.015693,0.101314,-0.038749,-0.044285,-0.037089,0.052060,0.006955,0.077752,1.000000,0.040348,0.111265,0.050260,0.087068,0.048986,0.617630,0.097344
totChol,-0.070413,0.262554,-0.023613,-0.046488,-0.026479,0.080623,0.000105,0.163632,0.040348,1.000000,0.208734,0.164698,0.115992,0.091127,0.046538,0.082369
sysBP,-0.035879,0.394053,-0.129496,-0.130281,-0.088797,0.254194,0.057000,0.696656,0.111265,0.208734,1.000000,0.783952,0.326906,0.182155,0.140573,0.216374
diaBP,0.058199,0.205586,-0.061919,-0.107933,-0.056715,0.194122,0.045153,0.615840,0.050260,0.164698,0.783952,1.000000,0.377360,0.181021,0.061075,0.145112
BMI,0.081871,0.136096,-0.137747,-0.167857,-0.093293,0.100702,0.025909,0.301344,0.087068,0.115992,0.326906,0.377360,1.000000,0.067451,0.087389,0.075300
heartRate,-0.116932,-0.012843,-0.054182,0.062686,0.075564,0.015230,-0.017674,0.146815,0.048986,0.091127,0.182155,0.181021,0.067451,1.000000,0.094546,0.022907
glucose,0.005979,0.122356,-0.035843,-0.056726,-0.058886,0.051197,0.018440,0.086656,0.617630,0.046538,0.140573,0.061075,0.087389,0.094546,1.000000,0.125590
TenYearCHD,0.088374,0.225408,-0.054248,0.019448,0.057755,0.087519,0.061823,0.177458,0.097344,0.082369,0.216374,0.145112,0.075300,0.022907,0.125590,1.000000

In [7]:
df.describe()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,4240.000000,4240.000000,4135.000000,4240.000000,4211.000000,4187.000000,4240.000000,4240.000000,4240.000000,4190.000000,4240.000000,4240.000000,4221.000000,4239.000000,3852.000000,4240.000000
mean,0.429245,49.580189,1.979444,0.494104,9.005937,0.029615,0.005896,0.310613,0.025708,236.699523,132.354599,82.897759,25.800801,75.878981,81.963655,0.151887
std,0.495027,8.572942,1.019791,0.500024,11.922462,0.169544,0.076569,0.462799,0.158280,44.591284,22.033300,11.910394,4.079840,12.025348,23.954335,0.358953
min,0.000000,32.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.070000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,3.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,144.000000,90.000000,28.040000,83.000000,87.000000,0.000000
max,1.000000,70.000000,4.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [8]:
df['age'].unique()

array([39, 46, 48, 61, 43, 63, 45, 52, 50, 41, 38, 42, 44, 47, 60, 35, 36,
       59, 54, 37, 56, 53, 49, 65, 51, 62, 40, 67, 57, 66, 64, 55, 58, 34,
       68, 33, 70, 32, 69])

In [9]:
df['education'].unique()

array([ 4.,  2.,  1.,  3., nan])

In [10]:
df['currentSmoker'].unique()

array([0, 1])

In [11]:
df['cigsPerDay'].unique()

array([ 0., 20., 30., 23., 15.,  9., 10.,  5., 35., 43.,  1., 40.,  3.,
        2., nan, 12.,  4., 18., 25., 60., 14., 45.,  8., 50., 13., 11.,
        7.,  6., 38., 29., 17., 16., 19., 70.])

In [12]:
df['BPMeds'].unique()

array([ 0.,  1., nan])

In [13]:
df['prevalentStroke'].unique()

array([0, 1])

In [14]:
df['prevalentHyp'].unique()

array([0, 1])

In [15]:
df['diabetes'].unique()

array([0, 1])

In [16]:
df['totChol'].unique()

array([195., 250., 245., 225., 285., 228., 205., 313., 260., 254., 247.,
       294., 332., 226., 221., 232., 291., 190., 185., 234., 215., 270.,
       272., 295., 209., 175., 214., 257., 178., 233., 180., 243., 237.,
        nan, 311., 208., 252., 261., 179., 194., 267., 216., 240., 266.,
       255., 220., 235., 212., 223., 300., 302., 248., 200., 189., 258.,
       202., 213., 183., 274., 170., 210., 197., 326., 188., 256., 244.,
       193., 239., 296., 269., 275., 268., 265., 173., 273., 290., 278.,
       264., 282., 241., 288., 222., 303., 246., 150., 187., 286., 154.,
       279., 293., 259., 219., 230., 320., 312., 165., 159., 174., 242.,
       301., 167., 308., 325., 229., 236., 224., 253., 464., 171., 186.,
       227., 249., 176., 163., 191., 263., 196., 310., 164., 135., 238.,
       207., 342., 287., 182., 352., 284., 217., 203., 262., 129., 155.,
       323., 206., 283., 319., 304., 340., 328., 280., 368., 218., 276.,
       339., 231., 198., 177., 201., 277., 184., 199., 168., 292., 305.,
       306., 152., 161., 181., 251., 271., 370., 439., 145., 330., 157.,
       398., 162., 314., 166., 160., 281., 289., 355., 307., 156., 329.,
       143., 211., 298., 334., 192., 204., 318., 309., 353., 360., 335.,
       158., 372., 346., 169., 140., 324., 600., 315., 392., 322., 149.,
       137., 172., 317., 358., 153., 345., 391., 410., 297., 356., 338.,
       107., 148., 366., 333., 327., 344., 126., 365., 362., 316., 144.,
       351., 390., 321., 405., 359., 350., 336., 380., 299., 124., 371.,
       113., 354., 382., 364., 341., 133., 367., 432., 337., 696., 363.,
       331., 361., 453., 347., 373., 385., 119.])

In [17]:
df['sysBP'].unique()

array([106. , 121. , 127.5, 150. , 130. , 180. , 138. , 100. , 141.5,
       162. , 133. , 131. , 142. , 124. , 114. , 140. , 112. , 122. ,
       139. , 108. , 123.5, 148. , 132. , 137.5, 102. , 110. , 182. ,
       115. , 134. , 147. , 124.5, 153.5, 160. , 153. , 111. , 116.5,
       206. ,  96. , 179.5, 119. , 116. , 156.5, 145. , 143.5, 158. ,
       157. , 126.5, 136. , 154. , 190. , 107. , 112.5, 164.5, 138.5,
       155. , 151. , 152. , 179. , 113. , 200. , 132.5, 126. , 123. ,
       141. , 135. , 187. , 127. , 160.5, 105. , 109. , 128. , 118. ,
       109.5, 117.5, 149. , 180.5, 136.5, 212. , 125. , 191. , 121.5,
       173. , 144. , 129.5, 117. , 144.5, 170. , 137. ,  94. , 119.5,
       143. , 166. , 139.5, 177.5, 129. , 159. , 130.5, 107.5, 189. ,
       168. , 197.5, 146. , 174. , 122.5,  98. , 131.5, 195. , 101. ,
       158.5,  97. , 151.5,  97.5, 120. , 204. , 157.5, 140.5, 171. ,
       215. ,  95. , 156. , 165. , 178. , 146.5, 113.5, 188. , 197. ,
        90. , 152.5,  95.5, 209. , 162.5, 295. , 108.5, 103. , 145.5,
       134.5, 115.5, 118.5, 174.5, 163. , 185. , 220. , 164. , 120.5,
        98.5, 161. , 168.5, 176. , 163.5, 128.5, 167. , 205.5, 167.5,
       172.5, 183. , 186. , 147.5, 175. , 142.5, 192. ,  96.5, 159.5,
       177. , 102.5, 133.5, 244. , 104. , 213. , 199. , 184. , 198. ,
       114.5, 125.5, 111.5, 105.5, 161.5, 171.5, 201. , 148.5, 169. ,
       154.5,  93.5, 172. , 243. , 187.5,  99. , 181. , 100.5, 104.5,
       135.5, 185.5, 103.5, 149.5, 182.5, 186.5, 217. , 196. , 193. ,
       110.5, 155.5,  92. , 166.5, 202. , 150.5, 232. ,  85.5, 184.5,
       235. , 205. , 169.5, 210. , 181.5, 188.5, 176.5,  92.5, 202.5,
       191.5, 208. ,  83.5, 106.5, 170.5,  93. , 175.5, 207.5, 199.5,
       101.5, 248. ,  99.5,  85. , 230. , 214. , 192.5, 194. , 207. ])

In [18]:
df['diaBP'].unique()

array([ 70. ,  81. ,  80. ,  95. ,  84. , 110. ,  71. ,  89. , 107. ,
        76. ,  88. ,  94. ,  64. ,  90. ,  78. ,  84.5,  70.5,  77.5,
        82. ,  68. ,  72.5,  91. , 121. ,  85.5,  85. ,  82.5,  74. ,
        92.5, 102. ,  98. , 101. ,  73. ,  92. ,  83.5,  63. , 114. ,
        69. ,  93. ,  66. ,  75. ,  79. ,  87. ,  99. ,  60. ,  67.5,
       106. ,  86.5, 104. ,  86. ,  61.5,  71.5,  76.5,  77. ,  88.5,
       105. ,  96. ,  97. , 100. ,  81.5, 106.5,  80.5, 124.5,  61. ,
        83. ,  67. ,  74.5,  66.5,  65. ,  72. ,  99.5, 122.5,  57. ,
        57.5, 111. ,  78.5, 104.5,  89.5, 112. ,  55. , 123. , 120. ,
        75.5, 118. ,  97.5,  59. , 133. ,  69.5,  95.5,  96.5, 135. ,
        64.5,  68.5,  98.5,  62. , 117. ,  59.5, 103. , 108.5,  73.5,
        87.5, 108. ,  93.5,  90.5, 114.5,  62.5,  94.5, 140. , 124. ,
        79.5, 109. ,  91.5, 115. , 102.5,  65.5, 105.5, 103.5,  63.5,
       107.5, 142.5, 109.5,  58. , 117.5, 116.5, 100.5, 116. , 119. ,
        54. , 132. ,  50. , 101.5, 136. ,  51. , 128. , 125. , 112.5,
       130. , 110.5, 113. ,  53. , 129. ,  52. ,  48. ,  56. ,  60.5,
       115.5, 127.5])

In [19]:
df['BMI'].unique()

array([26.97, 28.73, 25.34, ..., 26.7 , 43.67, 20.91], shape=(1365,))

In [20]:
df['heartRate'].unique()

array([ 80.,  95.,  75.,  65.,  85.,  77.,  60.,  79.,  76.,  93.,  72.,
        98.,  64.,  70.,  71.,  62.,  73.,  90.,  96.,  68.,  63.,  88.,
        78.,  83., 100.,  67.,  84.,  57.,  50.,  74.,  86.,  55.,  92.,
        66.,  87., 110.,  81.,  56.,  89.,  82.,  48., 105.,  61.,  54.,
        69.,  52.,  94., 140., 130.,  58., 108., 104.,  91.,  53.,  nan,
       106.,  59.,  51., 102., 107., 112., 125., 103.,  44.,  47.,  45.,
        97., 122., 120.,  99., 115., 143., 101.,  46.])

In [21]:
df['glucose'].unique()

array([ 77.,  76.,  70., 103.,  85.,  99.,  78.,  79.,  88.,  61.,  64.,
        84.,  nan,  72.,  89.,  65., 113.,  75.,  83.,  66.,  74.,  63.,
        87., 225.,  90.,  80., 100., 215.,  98.,  62.,  95.,  94.,  55.,
        82.,  93.,  73.,  45., 202.,  68.,  97., 104.,  96., 126., 120.,
       105.,  71.,  56.,  60., 117., 102.,  58.,  92., 109.,  86., 107.,
        54.,  67.,  69.,  57.,  91., 132., 150.,  59.,  81., 115., 140.,
       112., 118., 143., 114., 160., 110., 123., 108., 145., 122., 137.,
       106., 127., 205., 130., 101.,  47.,  53., 216., 163., 144., 116.,
       121., 172., 124., 111.,  40., 186., 223., 325.,  44., 156., 268.,
        50., 274., 292., 255., 136., 206., 131., 148., 297.,  43., 173.,
        48., 386., 155., 147., 170.,  52., 320., 254., 394., 270., 244.,
       183., 142., 119., 135., 167., 207., 129., 177., 250., 294., 166.,
       125., 332., 368., 348., 248., 370., 193., 191., 256., 235., 210.,
       260.])

In [22]:
df['TenYearCHD'].unique()

array([0, 1])

In [23]:
df.isnull().sum().sum()

np.int64(645)

In [24]:
df = df.fillna(df.median(numeric_only=True))

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   education        4240 non-null   float64
 3   currentSmoker    4240 non-null   int64
 4   cigsPerDay       4240 non-null   float64
 5   BPMeds           4240 non-null   float64
 6   prevalentStroke  4240 non-null   int64
 7   prevalentHyp     4240 non-null   int64
 8   diabetes         4240 non-null   int64
 9   totChol          4240 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4240 non-null   float64
 13  heartRate        4240 non-null   float64
 14  glucose          4240 non-null   float64
 15  TenYearCHD       4240 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 530.1 KB

In [26]:

# Features (X) and target (y)
X = df.drop("TenYearCHD", axis=1)   # target column remove
y = df["TenYearCHD"]                 # target column

# 80-20 split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,      # 20% testing
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(3392, 15)
(848, 15)

In [27]:
train_df = X_train.copy()
train_df["TenYearCHD"] = y_train
val_df = X_test.copy()
val_df["TenYearCHD"] = y_test

In [28]:
def dataframe_to_dataset(df):
    df = df.copy()
    labels = df.pop('TenYearCHD')
    ds = tf.data.Dataset.from_tensor_slices(
        (dict(df), labels)
    )
    ds = ds.shuffle(buffer_size=len(df))
    return ds

In [29]:
train_ds = dataframe_to_dataset(train_df)
val_ds   = dataframe_to_dataset(val_df)
train_ds = train_ds.batch(32)
val_ds   = val_ds.batch(32)

In [30]:
from keras.utils import FeatureSpace

feature_space = FeatureSpace(
    features={
        # Categorical
        'male': 'integer_categorical',
        'currentSmoker': 'integer_categorical',
        'BPMeds': 'integer_categorical',
        'prevalentStroke': 'integer_categorical',
        'prevalentHyp': 'integer_categorical',
        'diabetes': 'integer_categorical',
        'education': 'integer_categorical',

        # Numerical
        'age': 'float_normalized',
        'cigsPerDay': 'float_normalized',
        'totChol': 'float_normalized',
        'sysBP': 'float_normalized',
        'diaBP': 'float_normalized',
        'BMI': 'float_normalized',
        'heartRate': 'float_normalized',
        'glucose': 'float_normalized',
    }
)


train_ds_with_no_labels = train_ds.map(lambda x, y: x)

feature_space.adapt(train_ds_with_no_labels)


for x, _ in train_ds.take(1):
    preprocessed_x = feature_space(x)
    print(preprocessed_x)

preprocessed_train_ds = train_ds.map(
    lambda x, y: (feature_space(x), y),
    num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

preprocessed_val_ds = val_ds.map(
    lambda x, y: (feature_space(x), y),
    num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

WARNING:tensorflow:From c:\Users\BEST LAPTOP\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\tensorflow\core.py:232: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

tf.Tensor(
[[-8.8358438e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   3.9974344e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -1.4973346e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00 -2.5130707e-01 -5.0999922e-01
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.0986505e+00 -4.1724366e-01]
 [-3.5139751e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.5692550e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -3.3232918e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00  5.4948114e-02  1.6653711e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -3.3527085e-01 -4.9628790e-02]
 [-1.3525896e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   5.1669461e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -1.2892979e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00  2.7370182e-01 -9.1658786e-02
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.1211028e+00 -7.3890668e-01]
 [-1.0838964e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   8.6754805e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00  3.7499550e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  3.1745255e-01  3.2668164e-01
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.7810446e-01  1.9298995e-02]
 [-2.8335515e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.1014503e+00 -9.5609007e-03  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -7.4840254e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -6.4506370e-01  1.5934548e-01
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -4.6998492e-01 -1.2214012e+00]
 [-4.5207541e-02  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.2184016e+00  7.4240521e-02  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -2.4911453e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00 -7.6304108e-02 -1.5140163e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -4.6998492e-01 -2.3343623e-01]
 [-1.0002285e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -3.0196351e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00  8.3744161e-02  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -5.1381153e-01 -5.9366733e-01
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -2.6791382e-01  1.1910714e+00]
 [-1.0634102e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.8501236e-01  2.8396873e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  2.5017351e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00 -2.5130707e-01 -1.1793439e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -7.3941302e-01 -1.4052086e+00]
 [-5.9787884e-02  0.0000000e+00  1.0000000e+00  0.0000000e+00
   5.1669461e-01  1.3312619e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -4.1077849e-02  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00 -8.2006669e-01 -9.1658786e-02
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  2.2603770e-01 -6.6997886e-01]
 [-2.3232324e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   7.5059688e-01  9.1225475e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  1.9976816e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  6.6745847e-01  3.2668164e-01
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  2.9427710e+00  1.0991677e+00]
 [-5.4580361e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   7.5059688e-01  9.1225475e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  1.6648229e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00 -6.8881446e-01 -9.2833966e-01
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  8.5470325e-01 -2.1046029e-01]
 [-8.9330494e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.3545239e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -9.1483188e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  5.4948114e-02  7.4502212e-01
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.4578879e+00 -1.1984253e+00]
 [ 1.0434680e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   2.0370595e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00  5.2948791e-04  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -7.7631593e-01 -9.1658786e-02
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -5.1488960e-01  1.4897585e+00]
 [ 2.2834826e-02  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.1014503e+00 -3.4476659e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -3.3232918e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -2.0755632e-01 -1.3466802e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -2.6791382e-01  3.8691387e-01]
 [ 1.1819824e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.0036705e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00  5.8303219e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  5.4948114e-02 -9.1658786e-02
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -3.8017553e-01 -7.1593076e-01]
 [ 4.9670035e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   3.9974344e-01  7.4240521e-02  0.0000000e+00  1.0000000e+00
   0.0000000e+00  5.2948791e-04  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -1.6380559e-01 -6.7733538e-01
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -7.3941302e-01  2.9602180e+00]
 [ 7.7372915e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.0036705e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00  5.2948791e-04  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -2.9505780e-01 -9.1658786e-02
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -6.4960366e-01  1.3289269e+00]
 [-1.1290224e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.2184016e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -8.2685180e-02  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -5.1381153e-01 -9.1658786e-02
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -2.0055680e-01  3.4096199e-01]
 [ 5.2586102e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -7.6976812e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -6.6518790e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  3.6120328e-01  3.2668164e-01
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -7.8431767e-01 -6.4700294e-01]
 [-2.4690405e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.4714751e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00  5.2948791e-04  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00 -3.8255930e-01 -1.5140163e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -8.7412703e-01 -2.1046029e-01]
 [-7.1104902e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.4714751e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -1.4973346e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  6.6745847e-01 -1.5976844e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.2782692e+00 -9.2271411e-01]
 [-6.1870575e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -4.1891468e-01 -3.4476659e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.6589986e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00  1.4244960e-01 -1.1793439e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.0537457e+00 -8.9973819e-01]
 [ 4.2379770e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.6584112e-01  9.1225475e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.1644759e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -4.2631003e-01  3.2668164e-01
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -2.0055680e-01  2.0310643e-01]
 [ 1.0313174e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.1206216e+00  7.4240521e-02  0.0000000e+00  1.0000000e+00
   0.0000000e+00  2.5017351e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00  9.8698854e-02  3.2668164e-01
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -3.3527085e-01  1.5357103e+00]
 [ 6.9596672e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   6.3364571e-01 -3.4476659e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  9.9910551e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00  1.1487166e+00 -9.1658786e-02
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  1.1377598e-01  6.5250851e-02]
 [ 2.6341256e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.6584112e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -3.3232918e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -2.5130707e-01  6.6135401e-01
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  8.5470325e-01  1.0991677e+00]
 [ 1.0545754e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   3.9974344e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -2.4911453e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.4244960e-01  7.5677387e-02
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -4.6998492e-01  1.1451195e+00]
 [-1.8386054e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   4.8889957e-02 -9.5609007e-03  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -2.4911453e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00 -1.6380559e-01 -1.0120077e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  6.8871297e-02 -6.2402701e-01]
 [-9.8669104e-02  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.0036705e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -1.7885859e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00 -2.5130707e-01  3.2668164e-01
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -5.1488960e-01  8.4643245e-01]
 [-1.2602469e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -1.7053773e+00 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -8.3161724e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00 -7.6304108e-02  1.1633625e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.1435552e+00  2.4905829e-01]
 [ 3.2110982e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
  -6.5281695e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00  2.3305402e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00 -6.4506370e-01  1.1633625e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00  2.2242961e+00  2.7203423e-01]
 [ 9.2925406e-01  0.0000000e+00  1.0000000e+00  0.0000000e+00
   6.3364571e-01 -7.6377368e-01  0.0000000e+00  0.0000000e+00
   1.0000000e+00 -4.9875852e-01  0.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00 -1.6380559e-01 -9.1658786e-02
   0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00
   1.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
   0.0000000e+00 -1.1884599e+00  2.0871327e+00]], shape=(32, 31), dtype=float32)

In [31]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(
    preprocessed_train_ds,
    validation_data=preprocessed_val_ds,
    epochs=10
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8119 - loss: 0.4755 - val_accuracy: 0.8573 - val_loss: 0.3910
Epoch 2/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8488 - loss: 0.3901 - val_accuracy: 0.8573 - val_loss: 0.3856
Epoch 3/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8505 - loss: 0.3821 - val_accuracy: 0.8608 - val_loss: 0.3816
Epoch 4/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8526 - loss: 0.3783 - val_accuracy: 0.8608 - val_loss: 0.3798
Epoch 5/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8538 - loss: 0.3753 - val_accuracy: 0.8550 - val_loss: 0.3808
Epoch 6/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8552 - loss: 0.3726 - val_accuracy: 0.8585 - val_loss: 0.3814
Epoch 7/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8532 - loss: 0.3717 - val_accuracy: 0.8526 - val_loss: 0.3815
Epoch 8/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8552 - loss: 0.3701 - val_accuracy: 0.8550 - val_loss: 0.3822
Epoch 9/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8567 - loss: 0.3686 - val_accuracy: 0.8550 - val_loss: 0.3808
Epoch 10/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8573 - loss: 0.3679 - val_accuracy: 0.8550 - val_loss: 0.3819

In [32]:
training_model = tf.keras.Sequential([
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

training_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

training_model.summary()

history = training_model.fit(
    preprocessed_train_ds,
    validation_data=preprocessed_val_ds,
    epochs=10
)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8467 - loss: 0.4163 - val_accuracy: 0.8550 - val_loss: 0.3797
Epoch 2/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8479 - loss: 0.3894 - val_accuracy: 0.8561 - val_loss: 0.3790
Epoch 3/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8496 - loss: 0.3838 - val_accuracy: 0.8561 - val_loss: 0.3818
Epoch 4/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8502 - loss: 0.3808 - val_accuracy: 0.8597 - val_loss: 0.3820
Epoch 5/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8517 - loss: 0.3777 - val_accuracy: 0.8573 - val_loss: 0.3830
Epoch 6/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8538 - loss: 0.3754 - val_accuracy: 0.8585 - val_loss: 0.3843
Epoch 7/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8550 - loss: 0.3738 - val_accuracy: 0.8585 - val_loss: 0.3826
Epoch 8/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8550 - loss: 0.3722 - val_accuracy: 0.8573 - val_loss: 0.3847
Epoch 9/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8529 - loss: 0.3708 - val_accuracy: 0.8561 - val_loss: 0.3872
Epoch 10/10
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8541 - loss: 0.3702 - val_accuracy: 0.8573 - val_loss: 0.3860

In [33]:

for batch_x, _ in train_ds.take(1):
    example_batch = batch_x
    break

inputs = {
    key: tf.keras.Input(shape=(1,), name=key, dtype=value.dtype)
    for key, value in example_batch.items()
}

def preprocess_fn(inputs):
    return feature_space(inputs)
x = tf.keras.layers.Lambda(preprocess_fn)(inputs)
outputs = training_model(x)
inference_model = tf.keras.Model(inputs=inputs, outputs=outputs)
inference_model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ BMI (InputLayer)    │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ BPMeds (InputLayer) │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ age (InputLayer)    │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cigsPerDay          │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ currentSmoker       │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ diaBP (InputLayer)  │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ diabetes            │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ education           │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ glucose             │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ heartRate           │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ male (InputLayer)   │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ prevalentHyp        │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ prevalentStroke     │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ sysBP (InputLayer)  │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ totChol             │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lambda (Lambda)     │ (None, 31)        │          0 │ BMI[0][0],        │
│                     │                   │            │ BPMeds[0][0],     │
│                     │                   │            │ age[0][0],        │
│                     │                   │            │ cigsPerDay[0][0], │
│                     │                   │            │ currentSmoker[0]… │
│                     │                   │            │ diaBP[0][0],      │
│                     │                   │            │ diabetes[0][0],   │
│                     │                   │            │ education[0][0],  │
│                     │                   │            │ glucose[0][0],    │
│                     │                   │            │ heartRate[0][0],  │
│                     │                   │            │ male[0][0],       │
│                     │                   │            │ prevalentHyp[0][… │
│                     │                   │            │ prevalentStroke[… │
│                     │                   │            │ sysBP[0][0],      │
│                     │                   │            │ totChol[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ sequential_1        │ (None, 1)         │      1,569 │ lambda[0][0]      │
│ (Sequential)        │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,569 (6.13 KB)

 Trainable params: 1,569 (6.13 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
#Model training
training_model.fit(
    preprocessed_train_ds,
    validation_data=preprocessed_val_ds,
    epochs=10,
    verbose=2

)

Epoch 1/10
106/106 - 2s - 23ms/step - accuracy: 0.8558 - loss: 0.3690 - val_accuracy: 0.8561 - val_loss: 0.3858
Epoch 2/10
106/106 - 2s - 21ms/step - accuracy: 0.8555 - loss: 0.3672 - val_accuracy: 0.8526 - val_loss: 0.3849
Epoch 3/10
106/106 - 2s - 22ms/step - accuracy: 0.8561 - loss: 0.3663 - val_accuracy: 0.8538 - val_loss: 0.3857
Epoch 4/10
106/106 - 4s - 36ms/step - accuracy: 0.8555 - loss: 0.3647 - val_accuracy: 0.8538 - val_loss: 0.3870
Epoch 5/10
106/106 - 4s - 34ms/step - accuracy: 0.8567 - loss: 0.3633 - val_accuracy: 0.8526 - val_loss: 0.3862
Epoch 6/10
106/106 - 1s - 12ms/step - accuracy: 0.8558 - loss: 0.3633 - val_accuracy: 0.8526 - val_loss: 0.3921
Epoch 7/10
106/106 - 1s - 9ms/step - accuracy: 0.8585 - loss: 0.3609 - val_accuracy: 0.8491 - val_loss: 0.3885
Epoch 8/10
106/106 - 1s - 10ms/step - accuracy: 0.8579 - loss: 0.3594 - val_accuracy: 0.8526 - val_loss: 0.3895
Epoch 9/10
106/106 - 3s - 26ms/step - accuracy: 0.8591 - loss: 0.3592 - val_accuracy: 0.8538 - val_loss: 0.3889
Epoch 10/10
106/106 - 1s - 9ms/step - accuracy: 0.8597 - loss: 0.3572 - val_accuracy: 0.8514 - val_loss: 0.3908

In [37]:
sample= {
    'male': 1,
    'age': 65.0,
    'education': 1,
    'currentSmoker': 1,
    'cigsPerDay': 25.0,
    'BPMeds': 1,
    'prevalentStroke': 1,
    'prevalentHyp': 1,
    'diabetes': 1,
    'totChol': 300.0,
    'sysBP': 180.0,
    'diaBP': 110.0,
    'BMI': 35.0,
    'heartRate': 95.0,
    'glucose': 180.0
}

In [38]:
input_dict = {
    name: tf.convert_to_tensor([value])
    for name, value in sample.items()
}

In [39]:
prediction = inference_model.predict(input_dict)

print(
    f"This patient has a {100 * prediction[0][0]:.2f}% probability "
    "of having heart disease."
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 588ms/step
This patient has a 89.72% probability of having heart disease.

In [40]:
inference_model.save("heart_disease_model.keras")